mod component;
mod entities;
mod query;
mod error;
pub use error::{P1Error, EntityError, ComponentError};
pub use component::{Component, ComponentBitmask};
pub(crate) use component::ComponentIndexer;
pub(crate) use entities::EntityManager;
pub use query::Query;
pub(crate) use query::{QueryData, Mut, Ref};
