[package]
name = "macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = "2.0.65"
indexmap = "2.6.0"
parking_lot = "0.12.3"
proc-macro2 = "1.0.94"
